name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SetUp Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Generate changelog and push changes
        run: | 
            git config --global user.email "contact@danni.cool"
            git config --global user.name "gitHubCi"
            npx standard-version
            git add .
            git commit -m "Commit changes for release"
            git push --follow-tags origin main && npm publish

      - name: Extract Latest Changelog
        id: extract_changelog
        run: |
          LATEST_CHANGELOG=$(sed -n '/^## \[.*\]/,/^## \[.*\]/p' CHANGELOG.md | sed '1d' | head -n -1)
          echo "::set-output name=changelog::$LATEST_CHANGELOG"

      - name: Get Package Version
        id: get_version
        run: echo "::set-output name=package_version::$(node -p "require('./package.json').version")"

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.package_version }}
          release_name: Release v${{ steps.get_version.outputs.package_version }}
          body: ${{ steps.extract_changelog.outputs.changelog }}
          draft: false
          prerelease: false