name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog and push changes
        run: | 
            git config --global user.email "contact@danni.cool"
            git config --global user.name "gitHubCi"
            npx standard-version

      - name: Push changes
        run: git push --follow-tags origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}